# Generated by Django 4.1.7 on 2023-03-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
