# Generated by Django 4.1.7 on 2023-03-17 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('phase_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('phase_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='subheading',
            fields=[
                ('subheading_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('subheading_name', models.CharField(max_length=50)),
                ('phase_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.phase')),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('info_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('info_link', models.URLField()),
                ('info_text', models.CharField(max_length=5000)),
                ('subheading_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subheading')),
            ],
        ),
    ]
