# Generated by Django 4.1.7 on 2023-04-13 05:46

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scraped_data',
            fields=[
                ('id', models.CharField(default=api.models.generate_unique_id, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('info', models.TextField()),
                ('curator_url', models.URLField()),
                ('gen_url', models.URLField()),
            ],
            options={
                'db_table': 'scraped_data',
            },
        ),
    ]
