# Generated by Django 4.1.7 on 2023-04-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='saved_data',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('main_header', models.CharField(max_length=30)),
                ('sub_header', models.CharField(max_length=30)),
                ('info', models.TextField()),
                ('gen_url', models.URLField()),
            ],
            options={
                'db_table': 'saved_data',
            },
        ),
    ]
