# Generated by Django 4.1.7 on 2023-04-13 06:19

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_saved_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminInfo',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'adminInfo',
            },
        ),
        migrations.CreateModel(
            name='headers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_header', models.IntegerField()),
                ('sub_header', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'headers',
            },
        ),
        migrations.AlterField(
            model_name='scraped_data',
            name='id',
            field=models.CharField(default=api.models.generate_unique_id, max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
