# Generated by Django 4.1.7 on 2023-04-15 06:19

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_admininfo_headers_alter_scraped_data_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved_data',
            name='curator_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='saved_data',
            name='id',
            field=models.CharField(default=api.models.generate_unique_id, max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
